name: mydeck
description: MyDeck application repository

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^0.9.2

  # Service locator
  get_it: ^4.0.0
  #state management
  flutter_bloc: ^6.0.1
  freezed_annotation: ^0.11.0
  # Value equality
  equatable: ^1.0.2
  # Functional programming thingies
  dartz: ^0.8.9
  rxdart: ^0.22.0
  # Remote API
  google_sign_in: ^4.4.4
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  jose: ^0.1.2+1
  json_serializable: ^3.3.0
  # Local cache
  floor: ^0.11.0
  sqflite: ^1.2.0
  shared_preferences: ^0.5.3+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Access to local storage
  path_provider: ^1.5.1
  dartkt: ^1.0.4
  #uuid generation
  uuid: ^2.0.4
  #beauty things
  flutter_styled_toast: ^1.2.1
  icon_shadow: ^1.0.1
  transparent_image: ^1.0.0
  animations: ^1.0.0+5
  colorful_safe_area: ^0.2.0
  flutter_swiper: ^1.1.6
  smooth_page_indicator: ^0.1.4
  
  #translation
  flutter_translate: ^1.5.7
  #image picker
  image_picker: ^0.6.3+1
  json_annotation: ^3.0.1
  

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  #tests
  build_runner: ^1.7.2
  freezed: ^0.10.4
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ^1.0.0
  bloc_test: ^7.0.0
  floor_generator: ^0.11.0
  #data structures
  stack: ^0.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/gavno.jpg
    - assets/mydeck_logo.svg
    - assets/my_deck_logo_big.png
  fonts:
    - family: 'Rubik One-Regular'
      fonts:
        - asset: fonts/RubikOne-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  localizely:
    project_id: 588d7769-62dc-4de1-84a8-c6e93d0c3c57
