/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData cards =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_progress =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribers_count =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_forward =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus =
      const IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
